groups:
    - firmware

recipes:
    global:
        - dotfiles::inputrc
    mac_os_x:
        - nodejs::default
        - osxdefaults::enable_standard_function_keys
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::finder_display_full_path
        - osxdefaults::enable_safari_debug_menu

attributes:
    git:
        name: Martijn Th√©
        email: martijn@pebble.com

    homebrewalt:
        apps:
            - ncdu
            - z
            - tree
            - openssl
            - bash-completion
            - mackup
            - mosh
        cask_apps:
            - alfred
            - spotify
            - flux
            - dash
            - synalyze-it-pro
            - plug
            - skype
            - gimp

